services:
    '@enhavo/app/action/ActionFactory':
        import: ActionFactory

    '@enhavo/app/action/ActionManager':
        import: ActionManager
        chunk: 'action'
        arguments:
            - '@enhavo/app/action/ActionFactory'
        tags:
            - { name: vue.service, service: 'actionManager' }

    '@enhavo/app/action/model/CloseAction':
        import: CloseAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/app/view-stack/EventDispatcher'
        tags:
            - { name: 'enhavo_app.action', class: 'CloseAction' }

    '@enhavo/app/action/model/DeleteAction':
        import: DeleteAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/app/view-stack/EventDispatcher'
            - '@enhavo/core/Translator'
        tags:
            - { name: 'enhavo_app.action', class: 'DeleteAction' }

    '@enhavo/app/action/model/DownloadAction':
        import: DownloadAction
        chunk: 'action'
        tags:
            - { name: 'enhavo_app.action', class: 'DownloadAction' }

    '@enhavo/app/action/model/DropdownAction':
        import: DropdownAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/action/ActionManager'
        tags:
            - { name: 'enhavo_app.action', class: 'dropdown' }

    '@enhavo/app/action/model/DuplicateAction':
        import: DuplicateAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/app/view-stack/EventDispatcher'
        tags:
            - { name: 'enhavo_app.action', class: 'DuplicateAction' }

    '@enhavo/app/action/model/EventAction':
        import: EventAction
        chunk: 'action'
        tags:
            - { name: 'enhavo_app.action', class: 'EventAction' }

    '@enhavo/app/action/model/FilterAction':
        import: FilterAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/filter/FilterManager'
            - '@enhavo/app/action/model/SingleFilterAction'
        tags:
            - { name: 'enhavo_app.action', class: 'FilterAction' }

    '@enhavo/app/action/model/ModalAction':
        import: ModalAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/modal/ModalManager'
        tags:
            - { name: 'enhavo_app.action', class: 'ModalAction' }

    '@enhavo/app/action/model/FormAction':
        import: FormAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/core/Router'
            - '@enhavo/app/modal/ModalManager'
            - '@enhavo/core/Translator'
        tags:
            - { name: 'enhavo_app.action', class: 'FormAction' }

    '@enhavo/app/action/model/OpenAction':
        import: OpenAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
        tags:
            - { name: 'enhavo_app.action', class: 'OpenAction' }

    '@enhavo/app/action/model/PreviewAction':
        import: PreviewAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/app/view-stack/EventDispatcher'
        tags:
            - { name: 'enhavo_app.action', class: 'PreviewAction' }

    '@enhavo/app/action/model/SaveAction':
        import: SaveAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/view/View'
            - '@enhavo/app/view-stack/EventDispatcher'
        tags:
            - { name: 'enhavo_app.action', class: 'SaveAction' }

    '@enhavo/app/action/model/SingleFilterAction':
        import: SingleFilterAction
        chunk: 'action'
        arguments:
            - '@enhavo/app/filter/FilterManager'
        tags:
            - { name: 'enhavo_app.action', class: 'SingleFilterAction' }

