imports:
    - path: '../*'

compiler_pass:
    action:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/app/action/ActionFactory'
        tag: 'enhavo_app.action'
    batch:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/app/batch/BatchFactory'
        tag: 'enhavo_app.batch'
    collection:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/app/collection/CollectionFactory'
        tag: 'enhavo_app.collection'
    column:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/app/column/ColumnFactory'
        tag: 'enhavo_app.column'
    filter:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/app/filter/FilterFactory'
        tag: 'enhavo_app.filter'
    form:
        path: '../../compiler-pass/registry.js'
        service: '@enhavo/app/form/FormRegistry'
        tag: 'enhavo_app.form'
    menu:
        path: '../../compiler-pass/registry.js'
        service: '@enhavo/app/menu/MenuRegistry'
        tag: 'enhavo_app.menu'
    modal:
        path: '../../compiler-pass/model-factory-register.js'
        service: '@enhavo/app/modal/ModalFactory'
        tag: 'enhavo_app.modal'
    view:
        path: '../../compiler-pass/registry.js'
        service: '@enhavo/app/view-stack/ViewRegistry'
        tag: 'enhavo_app.view'
    toolbar_widget:
        path: '../../compiler-pass/registry.js'
        service: '@enhavo/app/toolbar/widget/WidgetRegistry'
        tag: 'enhavo_app.toolbar'
    vue_factory:
        path: '@enhavo/app/compiler-pass/vue-factory.js'
        priority: 150

services:
    '@enhavo/core/Router':
        chunk: 'view'
        calls:
            - [setRoutingData, ['param:routes']]

    '@enhavo/core/Translator':
        chunk: 'view'
        calls:
            - [setData, ['param:translations']]
